<?php
/**
 * Icoders_Slider_Block_Banner
 *
 * @category  Icoders
 * @package   Icoders_Slider
 * @author    iCoders <support@icoders.co>
 * @copyright 2013 iCoders. (http://icodershill.com)
 * @license   Icoders License http://icodershill.com/licence
 * @link      http://www.icoders.hu
 */
/** @var $this Icoders_Slider_Block_Banner */
/** @var Icoders_Slider_Model_Banner $banner */
$banner = $this->getBanner('Cím vagy ID');
if ($banner->getId()):
    $slides = $banner->getSlides();
endif;
?>