<?php
/**
 * Aion_Rbanner_Block_Banner
 *
 * @category  Aion
 * @package   Aion_Rbanner
 * @author    Dombi István <istvan.dombi@aionhill.com>
 * @copyright 2013 AionNext Kft. (http://aionhill.com)
 * @license   Aion License http://aionhill.com/licence
 * @link      http://www.aion.hu
 */
/** @var $this Aion_Rbanner_Block_Banner */
/** @var Aion_Rbanner_Model_Banner $banner */
$banner = $this->getBanner('Cím vagy ID');
if ($banner->getId()):
    $slides = $banner->getSlides();
endif;
?>