<?php
/**
 * Icoders_Slider_Block_Banner
 *
 * @category  Icoders
 * @package   Icoders_Slider
 * @author    Kovacs Daniel Akos <daniel.kovacs@icodershill.com>
 * @copyright 2017 iCoders. (http://icodershill.com)
 * @license   Icoders License https://icodershill.com/licence
 * @link      https://icoders.co
 */

/** @var Icoders_Slider_Block_Banner $this */
/** @var Icoders_Slider_Model_Banner $banner */

$mobileHelper = Mage::helper('icoders_mobiledetect/data');
$banner       = $this->getBanner();

if ($banner->getId()) :
    $slides = $banner->getSlides(); ?>
    <div class="icoders-responsive-banner">
        <div class="container">
            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 no-padding">
                <div class="owl-carousel owl-theme" id="icodersResponsiveBanner">
                    <?php
                    foreach ($slides as $slide):
                        echo $this->getChild('banner_slide')->setSlide($slide)->toHtml();
                    endforeach;
                    ?>
                </div>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 no-padding">
                <?php echo $this->getChildHtml('small_banners'); ?>
            </div>

        </div>
    </div>

<?php endif; ?>

<div class="clearfix"></div>

<div class="container">
    <?php echo $this->getChildHtml('icon_banners'); ?>
</div>
