<?php
/**
 * Icoders_Banner template
 *
 * @category  Icoders
 * @package   Icoders_Banner
 * @author    Deli-Szabó Sándor <deli.szabo.sandor@icoders.hu>
 * @copyright 2014 iCoders. (http://www.icoders.hu)
 * @license   http://icoders.hu/license Icoders License
 * @link      http://www.icoders.hu
 */
?>
<?php $banner = $this->getBanner(); ?>
<?php if ($banner->getId()): ?>
    <?php $images = $banner->getImages(); ?>
    <?php $links = $banner->getLinks() ?>
    <?php if (count($links) > 0) : ?>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-banner-navbar-collapse-<?php echo $banner->getId() ?>">
                        <span class="sr-only"><?php echo $this->__('Toggle navigation') ?></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <div class="collapse navbar-collapse" id="bs-banner-navbar-collapse-<?php echo $banner->getId() ?>">
                    <ul class="nav navbar-nav">
                        <?php foreach($links as $link) : ?>
                            <li><a href="<?php echo $link->getLink() ?>" <?php if ($link->getTarget()) : echo 'target="' . $link->getTarget() . '"'; endif; ?>><?php echo $link->getTitle() ?> </a></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </nav>
    <?php endif; ?>


    <div id="banner-<?php echo $banner->getId() ?>" class="carousel slide" style="max-width: <?php echo $banner->getWidth(); ?>px;">

        <ol class="carousel-indicators">
            <?php for ($i = 0; $i < count($images); $i++) : ?>
                <li data-target="#banner-<?php echo $banner->getId() ?>" data-slide-to="<?php echo $i ?>" class="<?php echo ($i==0) ? 'active' : '' ?>"></li>
            <?php endfor; ?>
        </ol>

        <div class="carousel-inner">
            <?php $i=0; foreach ($images as $image): ?>
                <div class="<?php echo ($i==0) ? 'active ' : '' ?>item">
                    <img src="<?php echo $image->getImageUrl() ?>"/>
                    <div class="carousel-caption">
                        <h3><?php echo $image->getLabel() ?></h3>
                        <p><?php echo $image->getHtml() ?></p>
                    </div>
                </div>
                <?php $i++; endforeach; ?>
        </div>

        <a class="carousel-control left" href="#banner-<?php echo $banner->getId() ?>" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="carousel-control right" href="#banner-<?php echo $banner->getId() ?>" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>


    <script type="text/javascript">
        j = jQuery.noConflict();

        j(document).ready(function(){
            j("#banner-<?php echo $banner->getId() ?>").carousel(<?php echo $banner->getAdvancedSettings() ?>);

        })
    </script>

<?php endif; ?>