<?php
/**
 * @category  Aion
 * @package   Aion_Edm
 * @author    Sági Attila <sagi.attila@aionhill.hu>
 * @copyright 2016 AionNext Kft. (http://www.aionhill.hu)
 * @license   http://aionhill.hu/license Aion License
 * @link      http://www.aionhill.hu
 */

/**
 * @see Mage_Newsletter_Block_Subscribe
 * @var $this Mage_Newsletter_Block_Subscribe
 */
?>
<?php $helper = Mage::helper('aion_edm'); ?>
<div class="footer-newsletter-menu">
    <div class="container">
        <div class="block block-subscribe aion-edm-footer-block">
            <div class="">
                <div class="block-title"><?php echo $helper->__('Newsletter') ?></div>
                <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
                    <div class="block-content">
                        <div class="input-box">
                            <label><?php echo $this->__('Name') ?></label>
                            <input type="text"
                                   name="newsletter_name"
                                   id="newsletter_name"
                                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Name')) ?>"
                                   class="input-text required-entry validate-name"/>
                        </div>
                        <div class="input-box">
                            <label><?php echo $this->__('E-mail') ?></label>
                            <input type="text"
                                   name="email"
                                   id="newsletter"
                                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>"
                                   class="input-text required-entry validate-email"/>
                        </div>
                        <div class="actions">
                            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="button">
                                <span><span><?php echo $this->__('Subscribe') ?></span></span>
                            </button>
                        </div>

                        <div class="clearfix"></div>

                        <div class="checkbox aion-edm pull-right">
                            <label for="newsletter_accept">
                                <input type="checkbox"
                                       id="newsletter_accept"
                                       name="newsletter_accept"
                                       value="1"
                                       required="required">
                                <?php if ($helper->getTermsUrl()) : ?>
                                    <?php echo $helper->__('I accept <a href="%s" target="_blank">Terms and Conditions</a>.', $helper->getTermsUrl()); ?>
                                <?php else : ?>
                                    <?php echo $helper->__('I accept Terms and Conditions'); ?>
                                <?php endif; ?>
                            </label>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                </form>
                <script type="text/javascript">
                    //<![CDATA[
                    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
                    //]]>
                </script>
            </div>
        </div>
    </div>
</div>
