<?php
/**
 * Icoders_Banner template for Nila
 *
 * @category  Icoders
 * @package   Icoders_Banner
 * @author    Kovacs Daniel Akos <kovacs.daniel@icoders.hu>
 * @copyright 2016 iCoders. (http://www.icoders.hu)
 * @license   http://icoders.hu/license Icoders License
 * @link      http://www.icoders.hu
 */

$helper = Mage::helper('icoders_mobiledetect/data');
$banner = $this->getBanner();

if ($banner->getId()): ?>
    <?php $images = $banner->getImages(); ?>
    <?php $links = $banner->getLinks() ?>

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding-right">
            <div class="icoders-icoders-banner">
                <div class="icoders-banner-container">
                    <div id="banner-<?php echo $banner->getId() ?>" class="carousel slide" data-ride="carousel" style="width: 100%;">
                        <?php if (count($images) > 1): ?>
                            <ol class="carousel-indicators">
                                <?php for ($i = 0; $i < count($images); $i++) : ?>
                                    <li data-target="#banner-<?php echo $banner->getId() ?>" data-slide-to="<?php echo $i ?>" class="<?php echo ($i==0) ? 'active' : '' ?>"></li>
                                <?php endfor; ?>
                            </ol>
                        <?php endif; ?>

                        <div class="carousel-inner">
                            <?php $num = 0;
                            foreach ($images as $image): ?>
                                <div class="<?php if ($num == 0): ?>active<?php endif; ?> item">
                                    <a <?php if (!empty($image->getLink())): ?> href="<?php echo $image->getLink() ?>"<?php else: ?> href="#" <?php endif; ?>>
                                        <div class="caption-background" style="background-image: url('<?php echo $image->getImageUrl() ?>'); no-repeat center center fixed"></div>
                                    </a>
                                </div>
                                <?php $num++;
                            endforeach; ?>
                        </div>

                        <?php if (count($images) > 1): ?>
                            <div class="carousel-control-container">
                                <a class="carousel-control left" href="#banner-<?php echo $banner->getId() ?>" data-slide="prev">
                                    <i class="icon-nav fa fa-angle-left fa-3x"></i>
                                </a>
                                <a class="carousel-control right" href="#banner-<?php echo $banner->getId() ?>" data-slide="next">
                                    <i class="icon-nav fa fa-angle-right fa-3x"></i>
                                </a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>

<div class="container">
    <div class="icoders-icon-banners">
        <div class="icon-banner col-xs-12 col-sm-6 col-md-4">
            <div class="icon-banner-icon">
                <i class="icoders-icon icoders-icon-badge-freedelivery"></i>
            </div>
            <div class="icon-banner-text">
                <a href="#" title="<?php echo $this->__('Free Delivery'); ?>">
                    <?php echo $this->__('Free Delivery'); ?>
                </a>
                <div>
                    <?php echo $this->__('For orders above 100 EUR'); ?>
                </div>
            </div>
        </div>
        <div class="icon-banner col-xs-12 col-sm-6 col-md-4">
            <div class="icon-banner-icon">
                <i class="icoders-icon icoders-icon-badge-hotline"></i>
            </div>
            <div class="icon-banner-text">
                <a href="#" title="<?php echo $this->__('Trusted Service'); ?>">
                    <?php echo $this->__('Trusted Service'); ?>
                </a>
                <div>
                    <?php echo $this->__('Hotline and online service'); ?>
                </div>
            </div>
        </div>
        <div class="icon-banner col-xs-12 col-sm-12 col-md-4">
            <div class="icon-banner-icon">
                <i class="icoders-icon icoders-icon-badge-moneyback"></i>
            </div>
            <div class="icon-banner-text">
                <a href="#" title="<?php echo $this->__('Trusted Payment'); ?>">
                    <?php echo $this->__('Trusted Payment'); ?>
                </a>
                <div>
                    <?php echo $this->__('14 day money back guarantee'); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("#banner-<?php echo $banner->getId() ?>").carousel(<?php echo $banner->getAdvancedSettings() ?>);
    })
</script>

<?php endif; ?>

