<?php $bannerCollection = $this->_getCollection(); ?>
<?php if(($bannerCollection->count())>0) : ?>	
<?php $imageCollection = $this->_getBannerImageCollection($bannerCollection); ?>
<?php foreach ($imageCollection as $item) : ?>
	<?php 
		$height = $item['height']; 
		$width = $item['width']; 
		$content = $item['content']; 
		$advanced_settings = trim($item['advanced_settings']);		
		$images = $this->getSortedImages($content);
	?>
	<?php if(isset($images) && !empty($images) && count($images)>0) : ?>
		<link rel="stylesheet"  href="<?php echo $this->getSkinUrl('bannernext/supersized/css/supersized.css');?>"  type="text/css" media="screen" />
		<link rel="stylesheet"  href="<?php echo $this->getSkinUrl('bannernext/supersized/theme/supersized.shutter.css');?>"  type="text/css" media="screen" />
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('bannernext/supersized/js/jquery.easing.min.js') ?>" ></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('bannernext/supersized/js/supersized.3.2.6.min.js') ?>" ></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('bannernext/supersized/theme/supersized.shutter.min.js') ?>" ></script>
		<script type="text/javascript">	
			jQuery(function($){
				
				$.supersized({
					// Functionality
					slideshow               :   1,			// Slideshow on/off
					autoplay				:	1,			// Slideshow starts playing automatically
					start_slide             :   1,			// Start slide (0 is random)
					stop_loop				:	0,			// Pauses slideshow on last slide
					random					: 	0,			// Randomize slide order (Ignores start slide)
					slide_interval          :   3000,		// Length between transitions
					transition              :   6, 			// 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
					transition_speed		:	1000,		// Speed of transition
					new_window				:	1,			// Image links open in new window/tab
					pause_hover             :   0,			// Pause slideshow on hover
					keyboard_nav            :   1,			// Keyboard navigation on/off
					performance				:	1,			// 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
					image_protect			:	1,			// Disables image dragging and right click with Javascript
															   
					// Size & Position						   
					min_width		        :   0,			// Min width allowed (in pixels)
					min_height		        :   0,			// Min height allowed (in pixels)
					vertical_center         :   1,			// Vertically center background
					horizontal_center       :   1,			// Horizontally center background
					fit_always				:	0,			// Image will never exceed browser width or height (Ignores min. dimensions)
					fit_portrait         	:   1,			// Portrait images will not exceed browser height
					fit_landscape			:   0,			// Landscape images will not exceed browser width
															   
					// Components							
					slide_links				:	'blank',	// Individual links for each slide (Options: false, 'number', 'name', 'blank')
					thumb_links				:	1,			// Individual thumb links for each slide
					thumbnail_navigation    :   0,			// Thumbnail navigation	
					slides 					:  	
					[
			<?php $i=1; $total = count($images); foreach($images as $image):	?>
					{image : '<?php echo $this->helper('bannernext')->resizeImg($image['file']);?>', title : 'Image Credit: Maria Kazvan', thumb : '<?php echo $this->helper('bannernext')->resizeImg($image['file'],$width,$height);?>', url : '<?php echo $this->helper('bannernext')->resizeImg($image['file'],$width,$height);?>'}
					<?php if($i!=$total){ echo ',';} $i++; ?>
			<?php endforeach;?>
					]
				});
		    });

		</script>	
		
	<?php endif;?>
<?php endforeach;?>
<?php endif; ?>
